export const labelsEn = {
    appTitle: 'Civic Radar TN',
    dashboard: 'Overview',
    reportIssue: 'Fix My Area',
    myReports: 'My Complaints',
    analytics: 'Analytics',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    submit: 'Send Report',
    description: 'What is the problem?',
    location: 'Where is it?',
    analyzing: 'Reading your report...',
    status: 'Status',
    urgency: 'Urgency',
    category: 'Type',
    switchRole: 'Switch Mode',
    welcome: 'Hello, Citizen',
    welcomeAdmin: 'Welcome, Administrator',
    recentActivity: 'Recent Activity',
    issueDistribution: 'Issue Distribution',
    trendAnalysis: 'Trend Analysis',
    aiInsight: 'Smart Helper',
    noReports: 'No reports submitted yet.',
    enterDescription: 'e.g., No water in street tap, Garbage not collected',
    reports: 'Reports',
    resolved: 'Resolved',
    pending: 'Waiting',
    critical: 'Critical',
    sectors: 'Sectors',
    policies: 'Policies',
    alerts: 'Alerts',
    datasets: 'Datasets',
    
    // Citizen Navigation
    home: 'Home',
    schemes: 'Govt Benefits',
    eligibility: 'Check Eligibility',
    howToApply: 'How to Apply',
    
    // Schemes Page
    scheme_midday: 'Midday Meal Scheme',
    scheme_midday_desc: 'Free hot lunch for school children.',
    scheme_pds: 'Ration Shop (PDS)',
    scheme_pds_desc: 'Rice, sugar, and oil at low prices.',
    scheme_scholarship: 'Student Scholarship',
    scheme_scholarship_desc: 'Money for college students from backward classes.',
    learnMore: 'Read More',
    
    // Eligibility Page
    check_eligibility_title: 'Am I Eligible?',
    check_eligibility_desc: 'Answer 3 questions to find help.',
    age: 'Age',
    income: 'Yearly Family Income (₹)',
    occupation: 'Occupation',
    check_btn: 'Check Now',
    eligible_msg: 'You might get:',
    not_eligible_msg: 'No matching schemes found based on these answers.',
    
    // How to Apply
    steps_title: 'Simple Steps to Apply',
    step_1: 'Gather Documents',
    step_2: 'Visit Office / Website',
    step_3: 'Submit Form',
    docs_needed: 'Documents Needed:',
    aadhaar: 'Aadhaar Card',
    ration: 'Ration Card',
    income_cert: 'Income Certificate',
    
    // Report Issue
    report_title: 'Tell us about a problem',
    report_subtitle: 'We will send this to the right officer.',
    ai_category_detect: 'We detected this is about:',
    ai_urgency_detect: 'Priority Level:',

    // Admin Navigation
    ingestion: 'Data Ingestion',
    baseline: 'Baselines',
    deviations: 'Deviations',
    nlp: 'NLP Insights',
    fusion: 'Fusion Engine',
    
    // Admin Common
    advancedSettings: 'Advanced Settings',
    exportReport: 'Export Report',
    period: 'Time Period',
    region: 'Region',
    filter: 'Filter',
    lastUpdated: 'Last Updated',
    totalRecords: 'Total Records',
    score: 'Health Score',
    confidence: 'Confidence',
    evidence: 'Evidence',
    actions: 'Actions',
    upload: 'Upload Data',
    
    // Login Page
    login_state: 'Tamil Nadu',
    login_hero_title1: 'Government services,',
    login_hero_title2: 'simplified.',
    login_hero_desc: 'Access Tamil Nadu government schemes, check eligibility, report civic issues — all in one place.',
    login_feat1: 'Citizen Services',
    login_feat2: 'Secure & Verified',
    login_feat3: 'Tamil & English',
    login_welcome: 'Welcome to Civic Radar TN',
    login_signin: 'Sign in to continue',
    login_desc: 'Use your Google account to access government services. Government officials with @veltech.edu.in emails get admin access.',
    login_oauth_missing: 'Google OAuth not configured yet.',
    login_oauth_desc: 'Set NEXT_PUBLIC_GOOGLE_CLIENT_ID in environment variables.',
    login_authenticating: 'Authenticating...',
    login_how_works: 'How it works',
    login_step1_title: 'Sign in with Google',
    login_step1_desc: 'Quick, secure authentication',
    login_step2_title: 'Access services',
    login_step2_desc: 'Schemes, eligibility & more',
    login_step3_title: 'Report & track',
    login_step3_desc: 'Civic issues in your area',
    login_footer1: 'By signing in, you agree to the',
    login_footer_tos: 'Terms of Service',
    login_footer_and: 'and',
    login_footer_privacy: 'Privacy Policy'
};