export const labelsTa = {
    appTitle: 'குடிமை ரேடார் த.நா',
    dashboard: 'கண்ணோட்டம்',
    reportIssue: 'குறை தீர்க்க',
    myReports: 'எனது புகார்கள்',
    myIssues: 'என் புகார்கள்',
    analytics: 'பகுப்பாய்வு',
    settings: 'அமைப்புகள்',
    login: 'உள்நுழைய',
    logout: 'வெளியேறு',
    submit: 'அனுப்புக',
    description: 'என்ன பிரச்சனை?',
    location: 'எந்த இடம்?',
    analyzing: 'படிக்கிறது...',
    status: 'நிலை',
    urgency: 'அவசரம்',
    category: 'வகை',
    switchRole: 'முறை மாற்று',
    welcome: 'வணக்கம்',
    welcomeAdmin: 'வணக்கம், நிர்வாகி',
    recentActivity: 'சமீபத்திய செயல்பாடுகள்',
    issueDistribution: 'புகார் விநியோகம்',
    trendAnalysis: 'போக்கு பகுப்பாய்வு',
    aiInsight: 'ஸ்மார்ட் உதவியாளர்',
    noReports: 'இதுவரை எந்த புகாரும் சமர்ப்பிக்கப்படவில்லை.',
    noIssuesTitle: "நீங்கள் இன்னும் எந்த புகாரையும் பதிவு செய்யவில்லை.",
    noIssuesSubtitle: 'மாற்றத்தை உருவாக்கத் தொடங்குங்கள்!',
    enterDescription: 'எ.கா., தெரு குழாயில் தண்ணீர் இல்லை, குப்பை எடுக்கப்படவில்லை',
    reports: 'புகார்கள்',
    resolved: 'சரிசெய்யப்பட்டது',
    pending: 'நிலுவையில்',
    critical: 'மிக முக்கியம்',
    sectors: 'துறைகள்',
    policies: 'கொள்கைகள்',
    alerts: 'எச்சரிக்கைகள்',
    datasets: 'தரவுத்தொகுப்புகள்',

    // Citizen Navigation
    home: 'முகப்பு',
    schemes: 'அரசு நலத்திட்டங்கள்',
    eligibility: 'தகுதிச் சோதனை',
    howToApply: 'விண்ணப்பிப்பது எப்படி',
    volunteer: 'தன்னார்வலர்',
    
    // Citizen Dashboard
    recentUpdates: 'அறிவிப்புகள் & செய்திகள்',
    trackingIssues: 'புகார்களை கண்காணித்தல்',
    volunteerTitle: 'குடிமை தன்னார்வலராகுங்கள்',
    volunteerDesc: 'உங்கள் சமூகத்தை மேம்படுத்த அரசுடன் கைகோர்க்கவும்.',
    applyVolunteer: 'விண்ணப்பிக்கவும்',
    noRecentIssues: 'கண்காணிக்க சமீபத்திய புகார்கள் இல்லை.',

    // Schemes Page
    scheme_midday: 'சத்துணவுத் திட்டம்',
    scheme_midday_desc: 'பள்ளி மாணவர்களுக்கு இலவச மதிய உணவு.',
    scheme_pds: 'நியாய விலைக் கடை (ரேஷன்)',
    scheme_pds_desc: 'அரிசி, சர்க்கரை மற்றும் எண்ணெய் குறைந்த விலையில்.',
    scheme_scholarship: 'மாணவர் உதவித்தொகை',
    scheme_scholarship_desc: 'கல்லூரி மாணவர்களுக்கான பண உதவி.',
    learnMore: 'மேலும் அறிய',

    // Eligibility Page
    check_eligibility_title: 'நான் தகுதியானவனா?',
    check_eligibility_desc: '3 கேள்விகளுக்கு பதிலளிக்கவும்.',
    age: 'வயது',
    income: 'ஆண்டு குடும்ப வருமானம் (₹)',
    occupation: 'தொழில்',
    check_btn: 'சோதிக்கவும்',
    eligible_msg: 'உங்களுக்கு கிடைக்கக்கூடியவை:',
    not_eligible_msg: 'தகுதியான திட்டங்கள் எதுவும் காணப்படவில்லை.',

    // How to Apply
    steps_title: 'விண்ணப்பிக்கும் முறை',
    step_1: 'ஆவணங்களைச் சேகரிக்கவும்',
    step_2: 'அலுவலகம் / இணையதளத்திற்குச் செல்லவும்',
    step_3: 'விண்ணப்பத்தை சமர்ப்பிக்கவும்',
    docs_needed: 'தேவையான ஆவணங்கள்:',
    aadhaar: 'ஆதார் அட்டை',
    ration: 'ரேஷன் அட்டை',
    income_cert: 'வருமான சான்றிதழ்',

    // Report Issue
    report_title: 'பிரச்சினையை சொல்லுங்கள்',
    report_subtitle: 'இதை சரியான அதிகாரியிடம் கொண்டு சேர்ப்போம்.',
    ai_category_detect: 'இது எதைப் பற்றியது:',
    ai_urgency_detect: 'முக்கியத்துவம்:',

    // Admin Navigation
    ingestion: 'தரவு உட்செலுத்துதல்',
    baseline: 'அடிப்படை அளவுகள்',
    deviations: 'விலகல்கள்',
    nlp: 'மொழி ஆய்வு',
    fusion: 'ஒருங்கிணைப்பு',

    // Admin Common
    advancedSettings: 'மேம்பட்ட அமைப்புகள்',
    exportReport: 'அறிக்கை ஏற்றுமதி',
    period: 'காலம்',
    region: 'மாவட்டம்',
    filter: 'வடிகட்டி',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    totalRecords: 'மொத்த பதிவுகள்',
    score: 'சுகாதார மதிப்பெண்',
    confidence: 'நம்பிக்கை',
    evidence: 'ஆதாரம்',
    actions: 'செயல்கள்',
    upload: 'பதிவேற்றம்',
    
    // Login Page
    login_state: 'தமிழ்நாடு',
    login_hero_title1: 'அரசு சேவைகள்,',
    login_hero_title2: 'எளிமையாக்கப்பட்டுள்ளன.',
    login_hero_desc: 'தமிழ்நாடு அரசு திட்டங்கள், தகுதி அறிய, மக்கள் குறைகளை தெரிவிக்க — அனைத்தும் ஒரே இடத்தில்.',
    login_feat1: 'குடிமக்கள் சேவைகள்',
    login_feat2: 'பாதுகாப்பானது',
    login_feat3: 'தமிழ் & ஆங்கிலம்',
    login_welcome: 'குடிமை ரேடார் த.நா விற்கு வருக',
    login_signin: 'தொடர உள்நுழையவும்',
    login_desc: 'அரசு சேவைகளை அணுக உங்கள் Google கணக்கை பயன்படுத்தவும். @veltech.edu.in மின்னஞ்சல் உள்ள அரசு அதிகாரிகள் நிர்வாகி அணுகல் பெறுவார்கள்.',
    login_oauth_missing: 'Google OAuth இன்னும் அமைக்கப்படவில்லை.',
    login_oauth_desc: 'NEXT_PUBLIC_GOOGLE_CLIENT_ID ஐ environment variables இல் அமைக்கவும்.',
    login_authenticating: 'உள்நுழைகிறது...',
    login_how_works: 'எப்படி செயல்படுகிறது',
    login_step1_title: 'Google மூலம் உள்நுழைக',
    login_step1_desc: 'விரைவான, பாதுகாப்பான உள்நுழைவு',
    login_step2_title: 'சேவைகளை அணுகவும்',
    login_step2_desc: 'திட்டங்கள், தகுதி மற்றும் பல',
    login_step3_title: 'புகாரளி & பின் தொடர்',
    login_step3_desc: 'உங்கள் பகுதியில் உள்ள குறைகள்',
    login_footer1: 'உள்நுழைவதன் மூலம், நீங்கள் ஏற்றுக்கொள்கிறீர்கள்:',
    login_footer_tos: 'சேவை விதிமுறைகள்',
    login_footer_and: 'மற்றும்',
    login_footer_privacy: 'தனியுரிமை கொள்கை'
};